### ISSUE TITLE
Name Lecture More Descriptively

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/ruby_lecture_review#1]
This repo might cover a ton of repo.

It's really "Ruby Language Basics"

and there should be a summary, in the README of what is covered in the video

(dot notation, methods, etc)

Otherwise great video :+1:

**Comment by AnnJohn** [comment]
Iceboxing the issue for now. The Readme was updated so the only thing that needs to be changed, if at all, is the title.
