### ISSUE TITLE
Video out of place

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co-curriculum/ruby_lecture_review#2]
Student points out that a bunch of things mentioned in this video have not yet actually been covered yet.

**Comment by kvignali** [comment]
agree with those students - I haven't learned most of the things in the video (even after a lot of the ruby lessons were reordered).

**Comment by aviflombaum** [comment]
Yep, @SophieDeBenedetto has a list and we'll move that video to the end of a unit once all those things like dot notation and others are covered.

**Comment by AnnJohn** [comment]
Closing issue
